export './views/auth/login/login_page.dart';
export './views/auth/register/register_page.dart';
export './views/landing/cart/cart_page.dart';
export './views/landing/cart/detail/cart_detail_page.dart';
export './views/landing/home/home_page.dart';
export './views/landing/landing_page.dart';
export './views/landing/products/categories/categories_page.dart';
// export 'landing/products/categories/detail/';
export './views/landing/products/detail/products_detail_page.dart';
export './views/landing/products/products_page.dart';
// export 'landing/products/widgets/products_screen.dart';
export './views/landing/profile/edit_profile/edit_profile_page.dart';
export './views/landing/profile/profile_page.dart';
// export 'core/wrapper/profile/profile_wrapper_page.dart';
export './views/landing/wishlist/wishlist_page.dart';
export './views/splash/splash_page.dart';
